# Generated by Django 3.2.4 on 2021-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='youtube.com/c/txtdrustadz'),
        ),
    ]
