# Generated by Django 3.2.4 on 2021-07-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonton', '0004_post_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255)),
        ),
    ]
